In [21]:
import pandas as pd
import numpy as np

In [22]:
df = pd.read_csv("data.csv")

In [34]:
df.drop(["Unnamed: 0"],axis=1,inplace=True)

In [35]:
df

,company,job_header,job_description
1,Microsoft,Consulting Services: Internship Opportunities,"At Microsoft, Interns work on real-world proje..."
2,Intact,Data Science - 4 Month Co-op/Internship (Winte...,It’s more than a great career. It’s a bright f...
3,Procter & Gamble,Digital Technologies Internship/Co-op (Jan 202...,Procter & Gamble is looking to develop the nex...
4,Splunk,Software Engineer - Early in Career,Join us as we pursue our disruptive new vision...
5,triOS College Business Technology Healthcare I...,Computer Programming Instructor - Toronto Sout...,triOS College Business Technology Healthcare I...
6,Intel,Software Engineer - PEY Intern,Job Description\nCome intern with one of the l...
7,Microsoft,Customer Success: Internship Opportunities,"At Microsoft, Interns work on real-world proje..."
8,OCAD University,"Undergraduate/Graduate Mitacs Internship, Myan...","Undergraduate/Graduate Mitacs Internship, Myan..."
9,TD Bank,Software Engineer Intern/Co-op,All companies are not the same. What makes TD ...
10,Bell Canada,ON - 2022 Field Services Operations General In...,"Req Id: 316002\n\nAt Bell, we do more than bui..."
11,Microsoft,Consulting Services: MBA Internship Opportunities,"At Microsoft, Interns work on real-world proje..."
12,"The Travelers Companies, Inc.",Actuarial Intern (January - April 2022),"Company Information\nSolid reputation, passion..."
13,Microsoft,Services – Customer Engineer: Internship Oppor...,"At Microsoft, Interns work on real-world proje..."
14,"Thales Canada Inc., Transportation Solutions",Software Analyst - Intern,"Location: Toronto, Canada\nThales people archi..."